---
- name: Install packages
  package:
    name: "{{ pkg }}"
    state: present
  with_items: "{{ mongodb_packages }}"
  loop_control:
    loop_var: pkg
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2
...
