---
# tasks file for mqtt
- name: install epel-release
  yum:
    name: epel-release.noarch
    state: latest
    
- name: install mosquitto
  yum:
    name: mosquitto
    state: latest

- name: config basic mosquitto
  template:
    src: "{{ path_home }}/roles/mqtt/templates/mosquitto.conf.j2"
    dest: "/etc/mosquitto/mosquitto.conf"
    owner: mosquitto
    group: mosquitto
    mode: "0644"

- name: create file acl_file
  template:
    src: "{{ path_home }}/roles/mqtt/templates/acl.conf.j2"
    dest: "/etc/mosquitto/acl.conf"
    owner: mosquitto
    group: mosquitto
    mode: "0644"

- name: create folder contain mosquitto.db
  file:
    path: /var/mosquitto/
    state: directory
    owner: mosquitto
    group: mosquitto
    mode: "0755"

- name: enable and start service
  systemd:
    daemon_reload: yes
    name: mosquitto
    state: started
    enabled: yes

- name: open port publish firewalld for mosquitto-exporter
  firewalld:
    port: 1883/tcp
    permanent: yes
    state: enabled

- name: open port subcribe firewalld for mosquitto-exporter
  firewalld:
    port: 2883/tcp
    permanent: yes
    state: enabled

- name: restart firewalld
  service: name=firewalld state=restarted
